### ISSUE TITLE
Questions about the INTERACTION test set

### ISSUE THREAD

**Issue by woyoudian2gou** [juanwulu/g-neva#1]
In the paper "Quantifying Uncertainty in Motion Prediction with Variational Bayesian Mixture," your method SeNeVA is compared with other methods in Table 1. However, the data you present is for the 'regular' scene type, while the data for other methods is for 'all' types. Is this comparison appropriate?

**Comment by juanwulu** [comment]
Hello, thanks for the comments. This is not the repository for the paper in your question. I will, therefore, close this issue as it is not relevant.

**Comment by juanwulu** [comment]
Hello, thanks for the comments. This is not the repository for the paper in your question. I will, therefore, close this issue as it is not relevant.

**Comment by woyoudian2gou** [comment]
> Hello, thanks for the comments. This is not the repository for the paper in your question. I will, therefore, close this issue as it is not relevant.

所以您所谓的repository for the paper in my question在哪？论文一accept就删库跑路了？心虚了？
